### PR TITLE
fix(dashboard): Use Timeseries instead of Graph

### PR DESCRIPTION
**Pull request by vimalk78**
fixes: #730

### CODE REVIEW

**Review by rdementi — APPROVED** [review]
thanks!

**Comment by vimalk78** [comment]
can someone confirm if ghcr.io image is updated with this change?
job: https://github.com/intel/pcm/actions/runs/8920527394/job/24498755594

**Comment by rdementi** [comment]
yes, it is. 
image

**Comment by vimalk78** [comment]
i cant pull 
```
$ docker pull ghcr.io/intel/pcm:latest 
Error response from daemon: Head "https://ghcr.io/v2/intel/pcm/manifests/latest": unauthorized
```

actually i have been using `ghcr.io/opcm/pcm:latest`

**Comment by rdementi** [comment]
please try to docker login with a token having read:packages permission 
image

**Comment by vimalk78** [comment]
i don't have credentials

**Comment by rdementi** [comment]
you can generate the token for you github user following this guide: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by vimalk78** [comment]
what is the relation with `ghcr.io/opcm/pcm:latest` image?

**Comment by rdementi** [comment]
I see the issue now. Thanks. The container referenced by the old name (ghcr.io/opcm/pcm:latest) of the repository is out of sync. Let me check how to fix it.

**Comment by vimalk78** [comment]
i logged in to `ghcr.io` , but still could not pull image. used my github token to login.

```
$ docker login ghcr.io
Username: vimalk78
Password: 

Login Succeeded

$ docker pull ghcr.io/intel/pcm:latest 
Error response from daemon: denied
```

**Comment by rdementi** [comment]
thanks for checking. The package seems to be hidden. I am trying to find out how this can be changed..

**Comment by rdementi** [comment]
> i logged in to `ghcr.io` , but still could not pull image. used my github token to login.
> 
> ```
> $ docker login ghcr.io
> Username: vimalk78
> Password: 
> 
> Login Succeeded
> 
> $ docker pull ghcr.io/intel/pcm:latest 
> Error response from daemon: denied
> ```

@vimalk78 please try to pull ghcr.io/intel/pcm:latest again. The organization just made this container public:
https://github.com/intel/pcm/pkgs/container/pcm

The ghcr.io/opcm/pcm container will be deleted to avoid double-maintenance and the users will need switch to  ghcr.io/intel/pcm

**Comment by vimalk78** [comment]
yes, i am able to pull `ghcr.io/intel/pcm:latest`

thanks a lot @rdementi !!

**Pull request merged**
